---
language: python
python: "2.7"
cache: pip

matrix:
  fast_finish: true

env:
  - TEST_RUN="ansible-playbook --syntax-check -i inventories/localhost site.yml"
  - TEST_RUN="ansible-playbook --list-hosts -i inventories/localhost site.yml"
  - TEST_RUN="ansible-playbook --list-tags -i inventories/localhost site.yml"
  - TEST_RUN="ansible-playbook --list-tasks -i inventories/localhost site.yml"

before_install:
  - pip install -U -r test-requirements.txt

install:
  - pip install -U -r requirements.txt

before_script:
  - find . -name '*.yml' -print0 | xargs -n1 -0 yamllint -c .yamllint.yml
  - ansible-lint site.yml

script: "$TEST_RUN"

notifications:
  email: false
