---
- name: Install required APT packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt_packages_before }}"

- name: Install keys for repository
  apt_key:
    id: "{{ item.id }}"
    url: "{{ item.url }}"
    state: present
  with_items: "{{ apt_repos }}"

- name: Add APT repositories
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
  with_items: "{{ apt_repos }}"

- name: Install more APT packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt_packages_after }}"
